const STATUS = {
  ASSASSIAN: 'assassian',
  AGENT: 'agent',
  NEUTRAL: 'neutral',
  UNKNOWN: 'unknown'
};

const REASON = {
  BAD_GUESS: 'bad guess',
  USED_GUESS: 'used all regular guesses',
  OUT_OF_GUESSES: 'used all regular guesses and catch up guess',
  BYSTANDER_GUESS: 'guessed a bystander',
  DEATH_GUESS: 'guessed an assassian',
  NOT_OVER: '',
  PASS: 'chose to pass',
};

const PHASE = {
  CLICK: 'click',
  CLUE: 'clue'
};

const DECK = [
  [STATUS.ASSASSIAN, STATUS.ASSASSIAN],
  [STATUS.ASSASSIAN, STATUS.AGENT],
  [STATUS.ASSASSIAN, STATUS.NEUTRAL],
  [STATUS.AGENT, STATUS.ASSASSIAN],
  [STATUS.NEUTRAL, STATUS.ASSASSIAN],
  [STATUS.AGENT, STATUS.AGENT],
  [STATUS.AGENT, STATUS.AGENT],
  [STATUS.AGENT, STATUS.AGENT],
  [STATUS.AGENT, STATUS.NEUTRAL],
  [STATUS.AGENT, STATUS.NEUTRAL],
  [STATUS.AGENT, STATUS.NEUTRAL],
  [STATUS.AGENT, STATUS.NEUTRAL],
  [STATUS.AGENT, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.AGENT],
  [STATUS.NEUTRAL, STATUS.AGENT],
  [STATUS.NEUTRAL, STATUS.AGENT],
  [STATUS.NEUTRAL, STATUS.AGENT],
  [STATUS.NEUTRAL, STATUS.AGENT],
  [STATUS.NEUTRAL, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.NEUTRAL]
];

const HOST_URL = 'http://localhost:2000';

module.exports = {STATUS, REASON, DECK, PHASE, HOST_URL};
