const STATUS = {
  ASSASIAN: 'assasian',
  AGENT: 'agent',
  NEUTRAL: 'neutral',
  UNKNOWN: 'unknown'
};

const REASON = {
  BAD_GUESS: 'bad guess',
  USED_GUESS: 'used all regular guesses',
  OUT_OF_GUESSES: 'used all regular guesses and catch up guess',
  BYSTANDER_GUESS: 'guessed a bystander',
  DEATH_GUESS: 'guessed an assasian',
  NOT_OVER: '',
  PASS: 'chose to pass',
};

const PHASE = {
  CLICK: 'click',
  CLUE: 'clue'
};

const DECK = [
  [STATUS.ASSASIAN, STATUS.ASSASIAN],
  [STATUS.ASSASIAN, STATUS.AGENT],
  [STATUS.ASSASIAN, STATUS.NEUTRAL],
  [STATUS.AGENT, STATUS.ASSASIAN],
  [STATUS.NEUTRAL, STATUS.ASSASIAN],
  [STATUS.AGENT, STATUS.AGENT],
  [STATUS.AGENT, STATUS.AGENT],
  [STATUS.AGENT, STATUS.AGENT],
  [STATUS.AGENT, STATUS.NEUTRAL],
  [STATUS.AGENT, STATUS.NEUTRAL],
  [STATUS.AGENT, STATUS.NEUTRAL],
  [STATUS.AGENT, STATUS.NEUTRAL],
  [STATUS.AGENT, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.AGENT],
  [STATUS.NEUTRAL, STATUS.AGENT],
  [STATUS.NEUTRAL, STATUS.AGENT],
  [STATUS.NEUTRAL, STATUS.AGENT],
  [STATUS.NEUTRAL, STATUS.AGENT],
  [STATUS.NEUTRAL, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.NEUTRAL],
  [STATUS.NEUTRAL, STATUS.NEUTRAL]
];

const HOST_URL = 'https://codename-duet-server.herokuapp.com';
const CLIENT_URL = 'http://codename-duet.herokuapp.com/';

const NEW_GAME_URL = `${HOST_URL}/make_new_game`

export {STATUS, REASON, DECK, PHASE, HOST_URL, NEW_GAME_URL, CLIENT_URL};
